<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="4" ignored="0" total="8" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-08-22T15:06:10 IST" name="Default suite" finished-at="2022-08-22T15:08:09 IST" duration-ms="119025">
    <groups>
    </groups>
    <test started-at="2022-08-22T15:06:10 IST" name="Default test" finished-at="2022-08-22T15:08:09 IST" duration-ms="119025">
      <class name="com.AttendanceManagement.Dashboard.AttendanceManagement">
        <test-method is-config="true" signature="configBS()[pri:0, instance:com.AttendanceManagement.Dashboard.AttendanceManagement@169e6180]" started-at="2022-08-22T15:06:10 IST" name="configBS" finished-at="2022-08-22T15:06:10 IST" duration-ms="6" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBS -->
        <test-method is-config="true" signature="configBC()[pri:0, instance:com.AttendanceManagement.Dashboard.AttendanceManagement@169e6180]" started-at="2022-08-22T15:06:10 IST" name="configBC" finished-at="2022-08-22T15:07:00 IST" duration-ms="49785" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBC -->
        <test-method is-config="true" signature="configBM()[pri:0, instance:com.AttendanceManagement.Dashboard.AttendanceManagement@169e6180]" started-at="2022-08-22T15:07:00 IST" name="configBM" finished-at="2022-08-22T15:07:06 IST" duration-ms="6302" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method signature="createClassTest()[pri:0, instance:com.AttendanceManagement.Dashboard.AttendanceManagement@169e6180]" started-at="2022-08-22T15:07:06 IST" name="createClassTest" finished-at="2022-08-22T15:07:15 IST" duration-ms="8911" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createClassTest -->
        <test-method is-config="true" signature="configAM()[pri:0, instance:com.AttendanceManagement.Dashboard.AttendanceManagement@169e6180]" started-at="2022-08-22T15:07:15 IST" name="configAM" finished-at="2022-08-22T15:07:16 IST" duration-ms="317" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAM -->
        <test-method is-config="true" signature="configBM()[pri:0, instance:com.AttendanceManagement.Dashboard.AttendanceManagement@169e6180]" started-at="2022-08-22T15:07:16 IST" name="configBM" finished-at="2022-08-22T15:07:16 IST" duration-ms="805" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method signature="SubmitAttendanceTest()[pri:2, instance:com.AttendanceManagement.Dashboard.AttendanceManagement@169e6180]" started-at="2022-08-22T15:07:16 IST" name="SubmitAttendanceTest" finished-at="2022-08-22T15:07:34 IST" duration-ms="17924" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitAttendanceTest -->
        <test-method is-config="true" signature="configAM()[pri:0, instance:com.AttendanceManagement.Dashboard.AttendanceManagement@169e6180]" started-at="2022-08-22T15:07:34 IST" name="configAM" finished-at="2022-08-22T15:07:35 IST" duration-ms="621" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAM -->
        <test-method is-config="true" signature="configBM()[pri:0, instance:com.AttendanceManagement.Dashboard.AttendanceManagement@169e6180]" started-at="2022-08-22T15:07:35 IST" name="configBM" finished-at="2022-08-22T15:07:35 IST" duration-ms="336" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method signature="CheckAttendanceOfStudentTest()[pri:0, instance:com.AttendanceManagement.Dashboard.AttendanceManagement@169e6180]" started-at="2022-08-22T15:07:35 IST" name="CheckAttendanceOfStudentTest" finished-at="2022-08-22T15:07:40 IST" depends-on-methods="com.AttendanceManagement.Dashboard.AttendanceManagement.SubmitAttendanceTest" duration-ms="5008" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckAttendanceOfStudentTest -->
        <test-method is-config="true" signature="configAM()[pri:0, instance:com.AttendanceManagement.Dashboard.AttendanceManagement@169e6180]" started-at="2022-08-22T15:07:40 IST" name="configAM" finished-at="2022-08-22T15:07:40 IST" duration-ms="172" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAM -->
        <test-method is-config="true" signature="configBM()[pri:0, instance:com.AttendanceManagement.Dashboard.AttendanceManagement@169e6180]" started-at="2022-08-22T15:07:41 IST" name="configBM" finished-at="2022-08-22T15:07:41 IST" duration-ms="315" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method retried="true" signature="VerifyAttendance()[pri:0, instance:com.AttendanceManagement.Dashboard.AttendanceManagement@169e6180]" started-at="2022-08-22T15:07:41 IST" name="VerifyAttendance" finished-at="2022-08-22T15:07:46 IST" depends-on-methods="com.AttendanceManagement.Dashboard.AttendanceManagement.CheckAttendanceOfStudentTest" duration-ms="4929" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.AttendanceManagement.Dashboard.AttendanceManagement.VerifyAttendance(AttendanceManagement.java:101)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyAttendance -->
        <test-method is-config="true" signature="configAM()[pri:0, instance:com.AttendanceManagement.Dashboard.AttendanceManagement@169e6180]" started-at="2022-08-22T15:07:46 IST" name="configAM" finished-at="2022-08-22T15:07:46 IST" duration-ms="145" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAM -->
        <test-method is-config="true" signature="configBM()[pri:0, instance:com.AttendanceManagement.Dashboard.AttendanceManagement@169e6180]" started-at="2022-08-22T15:07:46 IST" name="configBM" finished-at="2022-08-22T15:07:46 IST" duration-ms="323" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method retried="true" signature="VerifyAttendance()[pri:0, instance:com.AttendanceManagement.Dashboard.AttendanceManagement@169e6180]" started-at="2022-08-22T15:07:46 IST" name="VerifyAttendance" finished-at="2022-08-22T15:07:51 IST" depends-on-methods="com.AttendanceManagement.Dashboard.AttendanceManagement.CheckAttendanceOfStudentTest" duration-ms="4539" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.AttendanceManagement.Dashboard.AttendanceManagement.VerifyAttendance(AttendanceManagement.java:101)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyAttendance -->
        <test-method is-config="true" signature="configAM()[pri:0, instance:com.AttendanceManagement.Dashboard.AttendanceManagement@169e6180]" started-at="2022-08-22T15:07:51 IST" name="configAM" finished-at="2022-08-22T15:07:51 IST" duration-ms="221" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAM -->
        <test-method is-config="true" signature="configBM()[pri:0, instance:com.AttendanceManagement.Dashboard.AttendanceManagement@169e6180]" started-at="2022-08-22T15:07:51 IST" name="configBM" finished-at="2022-08-22T15:07:51 IST" duration-ms="384" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method retried="true" signature="VerifyAttendance()[pri:0, instance:com.AttendanceManagement.Dashboard.AttendanceManagement@169e6180]" started-at="2022-08-22T15:07:51 IST" name="VerifyAttendance" finished-at="2022-08-22T15:07:56 IST" depends-on-methods="com.AttendanceManagement.Dashboard.AttendanceManagement.CheckAttendanceOfStudentTest" duration-ms="4912" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.AttendanceManagement.Dashboard.AttendanceManagement.VerifyAttendance(AttendanceManagement.java:101)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyAttendance -->
        <test-method is-config="true" signature="configAM()[pri:0, instance:com.AttendanceManagement.Dashboard.AttendanceManagement@169e6180]" started-at="2022-08-22T15:07:56 IST" name="configAM" finished-at="2022-08-22T15:07:56 IST" duration-ms="141" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAM -->
        <test-method is-config="true" signature="configBM()[pri:0, instance:com.AttendanceManagement.Dashboard.AttendanceManagement@169e6180]" started-at="2022-08-22T15:07:56 IST" name="configBM" finished-at="2022-08-22T15:07:57 IST" duration-ms="338" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method retried="true" signature="VerifyAttendance()[pri:0, instance:com.AttendanceManagement.Dashboard.AttendanceManagement@169e6180]" started-at="2022-08-22T15:07:57 IST" name="VerifyAttendance" finished-at="2022-08-22T15:08:02 IST" depends-on-methods="com.AttendanceManagement.Dashboard.AttendanceManagement.CheckAttendanceOfStudentTest" duration-ms="5158" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.AttendanceManagement.Dashboard.AttendanceManagement.VerifyAttendance(AttendanceManagement.java:101)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyAttendance -->
        <test-method is-config="true" signature="configAM()[pri:0, instance:com.AttendanceManagement.Dashboard.AttendanceManagement@169e6180]" started-at="2022-08-22T15:08:02 IST" name="configAM" finished-at="2022-08-22T15:08:02 IST" duration-ms="205" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAM -->
        <test-method is-config="true" signature="configBM()[pri:0, instance:com.AttendanceManagement.Dashboard.AttendanceManagement@169e6180]" started-at="2022-08-22T15:08:02 IST" name="configBM" finished-at="2022-08-22T15:08:03 IST" duration-ms="415" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method signature="VerifyAttendance()[pri:0, instance:com.AttendanceManagement.Dashboard.AttendanceManagement@169e6180]" started-at="2022-08-22T15:08:03 IST" name="VerifyAttendance" finished-at="2022-08-22T15:08:08 IST" depends-on-methods="com.AttendanceManagement.Dashboard.AttendanceManagement.CheckAttendanceOfStudentTest" duration-ms="5066" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.AttendanceManagement.Dashboard.AttendanceManagement.VerifyAttendance(AttendanceManagement.java:101)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyAttendance -->
        <test-method is-config="true" signature="configAM()[pri:0, instance:com.AttendanceManagement.Dashboard.AttendanceManagement@169e6180]" started-at="2022-08-22T15:08:09 IST" name="configAM" finished-at="2022-08-22T15:08:09 IST" duration-ms="173" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAM -->
        <test-method is-config="true" signature="configAC()[pri:0, instance:com.AttendanceManagement.Dashboard.AttendanceManagement@169e6180]" started-at="2022-08-22T15:08:09 IST" name="configAC" finished-at="2022-08-22T15:08:09 IST" duration-ms="530" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAC -->
        <test-method is-config="true" signature="configAS()[pri:0, instance:com.AttendanceManagement.Dashboard.AttendanceManagement@169e6180]" started-at="2022-08-22T15:08:10 IST" name="configAS" finished-at="2022-08-22T15:08:10 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAS -->
      </class> <!-- com.AttendanceManagement.Dashboard.AttendanceManagement -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
